trigger:
  - main
pool:
  vmImage: ubuntu-latest

# sequences of parameters
parameters:
  - name: services
    type: object
    default:
      - artifactId: 'data-service'
        dockerRepo: 'some-data'
      - artifactId: 'engine-hours-scheduler-service'
        dockerRepo: 'some-engine-hours-scheduler'
  - name: other-services
    type: object
    default:
      - artifactId: 'data-service-2'
        dockerRepo: 'some-data-2'
      - artifactId: 'engine-hours-scheduler-service'
        dockerRepo: 'some-engine-hours-scheduler'
    values:
      - windows-latest
      - ubuntu-latest
      - macOS-latest

stages:
  - stage: 'Build'
    displayName: 'Build'
    jobs:
      - job: 'Build_And_Package'
        displayName: 'Build & package artifacts'
        pool:
          name: 'Agent'
        steps:
          - bash: echo "simple test"
          - checkout: self
            displayName: 'Git clone self repository'
