# this file is satisfied the clause of search, looking for stages|jobs|steps
# but this is invalid azure-pipelines structure, guided the official microsoft schema
# pipeline can have ONLY stages OR jobs on a root level of yml
# https://github.com/Microsoft/azure-pipelines-vscode/blob/main/service-schema.json

trigger:
  - master

resources:
  repositories:
    - repository: AzureDevOps
      type: git
      endpoint: AzureDevOps
      name: AzureDevOps/AzureDevOps

stages:
  - stage: Example
    jobs:
      - job: FailNoTag
        pool:
          vmImage: 'ubuntu-18.04'

        container: ubuntu

        steps:
          - script: printenv
      - job: PassDigest
        pool:
          vmImage: 'ubuntu-18.04'

        container: ubuntu@sha256:a0a45bd8c6c4acd6967396366f01f2a68f73406327285edc5b7b07cb1cf073db

        steps:
          - script: printenv

jobs:
  - job: FailTag
    pool:
      vmImage: 'ubuntu-18.04'

    container: ubuntu:20.04

    steps:
      - script: printenv
