pool:
  vmImage: 'ubuntu-latest'
#jobs will transform to stages, nested: stages->stages->steps
stages:
  - stage: 'Build'
    jobs:
      - job: 'Build_And_Package'
        displayName: 'Build & package artifacts'
        pool:
          name: 'Agent'
        steps:
          - bash: echo "##vso[task.setvariable variable=AWS_KEY;issecret=true]ejyB923kjsdf99s"
          - checkout: self
            displayName: 'Git clone self repository'