version: 2
jobs:
  run-tests:
    docker:
      - image: cimg/android:2022.09.2-ndk

    executor:
    machine:
    macos:
    steps:
      - run:
          name: "echo environment variables from project"
          command: echo $MY_ENV_VAR