trigger:
- main

environment:
  - moti: banana

  
pool: 
  vmImage: ubuntu-latest

jobs:
- job: PreWork
  steps:
  - script: "printenv"

- job: PostWork
  pool: windows-latest
  steps:
  - script: "Do post-work using a different hosted image"

  - script: echo "##vso[task.setvariable variable=AWS_KEY;issecret=true]ejyB923kjsdf99s"
    displayName: 'Define secret'