name: Docker Scanner Workflow

on:
  push:
    branches: [ main ]

jobs:
  scan:
    name: Run Cortex Scanner in Docker
    runs-on: ubuntu-latest

    env:
      CORTEX_CLI_VERSION: "latest"
      CORTEX_API_URL: "https://api.cortex.example.com"
      CORTEX_API_KEY: ${{ secrets.CORTEX_API_KEY }}
      CORTEX_API_KEY_ID: ${{ secrets.CORTEX_API_KEY_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Cortex CLI inside Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/home/code cortexcli:${{ env.CORTEX_CLI_VERSION }} \
            --api-base-url $CORTEX_API_URL \
            --api-key $CORTEX_API_KEY \
            --api-key-id $CORTEX_API_KEY_ID \
            code scan \
            --directory /home/code \
            --repo-id ${{ github.repository }} \
            --branch ${{ github.ref_name }} \
            --source 'GITHUB_ACTIONS' \
            --create-repo-if-missing
